# Generated by Django 3.1.6 on 2021-02-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_size', models.CharField(max_length=100, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AlterModelOptions(
            name='storageproduct',
            options={'verbose_name': 'Продукт магазина', 'verbose_name_plural': 'Продукты магазинов'},
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storageproduct',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.storage', verbose_name='Магазин'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.color', verbose_name='Цвет')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.product', verbose_name='Продукт')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
