# Generated by Django 3.1.6 on 2021-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20210225_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='color',
        ),
        migrations.RemoveField(
            model_name='options',
            name='good',
        ),
        migrations.RemoveField(
            model_name='options',
            name='size',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
